{{alias}}
direct	= +forward-override{forward .}
socks5	= +forward-override{forward-socks5 127.0.0.1:1080 .}
default = direct

# Default proxy 
{default}
/

{direct}
.edu.cn
.pi.lan

# Shadowsocks
{socks5}
.abc.xyz
.google.com.hk
.google.com
.1e100.net
.gmail.com
.googlemail.com
.googlemaps.com
.googlevideo.com
.goo.gl
.g.co
.googlezip.net
.google.org
.chrome.com
.google.net
.youtube.com
.youtu.be
.yt.be
.ytimg.com
.ggpht.com
.gstatic.com
.appspot.com
.googleapps.com
.googletagservices.com
.googletagmanager.com
.googlesyndication.com
.googleapis.com
.googles.com
.googleapis.cn
.gvt0.com
.gvt1.com
.gvt2.com
.gvt3.com
.xn--ngstr-lra8j.com
.googlecode.com
.googlegroups.com
.googleusercontent.com
.golang.org
.googlesource.com
.android.com
.android.gs
.dl.google.com
.blogger.com
.blogspot.com
.blogblog.com
.googlescholar.com
.tensorflow.org
.telegram.org
.telegram.me
.telegram.dog
.t.me
.wikipedia.org
.travis-ci.org
.live.com
.githubusercontent.com
.gist.github.com
.bitbucket.org
.dropbox.com
.dropboxstatic.com
.disqus.com
.amazonaws.com
.gogs.io
.w3schools.com
.stackoverflow.com
.stackexchange.com
.sstatic.net
.angular.io
.googletagservices.com
.npmjs.org
.thepiratebay.org
.pythonhosted.org
.slack.com
.bintray.com
.jfrog.org
.npmjs.org
.kali.org
.nativescript.org
.facebook.com
.facebook.net
.fbcdn.com
.fbcdn.net
.fb.com
.fb.me
.akamaihd.net
.fbsbx.com
.instagram.com
.cdninstagram.com
.edgekey.net
.edgesuite.net
.fbsbx.com
.xx.fbcdn.net
.tfbnw.net
.messenger.com
.amazonaws.com
.amazon.com
.ssl-images-amazon.com
.omtrdc.net
.developermedia.com
.piwheels.org
.pypi.org
.apache.org
.v2ex.com
.medium.com
.cloudfront.net
.ampproject.org
.material.io
.reddit.com
.redd.it
.redditstatic.com
.redditmedia.com
.quora.com
.quoracdn.net
.privoxy.org
.twrp.me
.apkmirror.com
.docker.io
